name: test-prosjekt1/pipeline-test

on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

env:
  DOCKER_USER: brennuvargur
  DOCKER_PASS: DetteErMittPassord

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim-buster
    timeout-minutes: 60
    env:
      IMAGE_NAME: brennuvargur/pipeline-test
      IMAGE_TAG: python-app-1.0
    steps:
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 20
          lfs: true

      - name: Install dependencies
        run: apt-get update && apt-get install make

      - name: Run tests
        run: make test

  build_image:
    needs: run_tests
    runs-on: ubuntu-latest
    container:
      image: docker:28.0.1-cli
    timeout-minutes: 60
    services:
      docker:
        image: docker:28.0.1-dind
    env:
      IMAGE_NAME: brennuvargur/pipeline-test
      IMAGE_TAG: python-app-1.0
      DOCKER_TLS_CERTDIR: "/certs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 20
          lfs: true

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
